name: CI
on: push

jobs:
  echo:
    name: Echo
    runs-on: [self-hosted,MacOS]
    steps:
    - name: Echo Hello
      env:
        SERVICE_NAME: JAVA
      run: |
        echo Hello $SERVICE_NAME
    
  after_echo:
    needs: [echo]
    name: After Echo
    runs-on: [self-hosted,MacOS]
    steps:
    - name: Echo After Echo
      run: |
        echo Show CPUU info on mac
        echo $(sysctl -a|grep machdep.cpu.brand_string)